// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelter.Models;

namespace Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    [Migration("20220401164342_Validations")]
    partial class Validations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 2,
                            Breed = "Red One",
                            Gender = "Male",
                            Name = "Sr.Waffles"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 5,
                            Breed = "Pink One",
                            Gender = "Male",
                            Name = "Senior Meowmeow"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 12,
                            Breed = "Black Cat",
                            Gender = "Male",
                            Name = "Frank the Tank"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 7,
                            Breed = "White Cat",
                            Gender = "Male",
                            Name = "Henry"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 4,
                            Breed = "I dont know cat breeds",
                            Gender = "Female",
                            Name = "Cat"
                        },
                        new
                        {
                            CatId = 6,
                            Age = 5,
                            Breed = "CodeCat",
                            Gender = "Male",
                            Name = "Epicat"
                        },
                        new
                        {
                            CatId = 7,
                            Age = 100,
                            Breed = "FatCat",
                            Gender = "Male",
                            Name = "Bill"
                        },
                        new
                        {
                            CatId = 8,
                            Age = 1,
                            Breed = "KittyCat",
                            Gender = "Male",
                            Name = "Phil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
